const STAGE_WIDTH = 625,
  STAGE_HEIGHT = 625,
  BOARD_CELLS_COUNT = 8,
  CELL_SIZE = 70,
  ANIMATION_SPEED = 5,
  LABEL_COLOR = '#fff',
  CELL_FIRST_COLOR = '#eee',
  CELL_SECOND_COLOR = '#B79F81',
  CELL_BORDER_COLOR = '#ccc',
  CELL_SELECTOR_COLOR = '#afa',
  FIGURES_SPRITE_NAME = 'figures.png'

export {
  STAGE_WIDTH,
  STAGE_HEIGHT,
  BOARD_CELLS_COUNT,
  CELL_SIZE,
  ANIMATION_SPEED,
  CELL_FIRST_COLOR,
  CELL_SECOND_COLOR,
  LABEL_COLOR,
  CELL_BORDER_COLOR,
  CELL_SELECTOR_COLOR,
  FIGURES_SPRITE_NAME
}
